(defun main()
(setq pal "PALENDROMEP")
(terpri)
(princ "Enter Function: ")
(setq read (read))
(print read)
(setq aList (first (last (first (last read)))))
(setq z (first read))
(setq fx (string z))
(print aList)
(print fx)
(cond ((equal pal fx) (palendromep aList)))
)

(defun palendromep( aList &optional a )
(terpri)
(print aList)
(terpri)
(cond
	((null aList) (print t))
	((atom aList) (print nil))
	((list aList) (print "TRUTH BE THERE")))
(setq f (first aList))
(setq l (first (last aList)))
(print (equal f l))
(cond
	((equal f l) (palendromep '(4))))
)

(main)
